### ISSUE TITLE
Allow option to remove animation while navigating back.

### ISSUE THREAD

**Issue by ludas96** [IeuanWalker/Xamarin.Forms.Breadcrumb#7]
I'm currently not using any animations while navigating through the app but instead while loading the page.

An option to remove animations (just a bool Property, like HasNavigateAnimation maybe) would be appreciated, or just any guidance on how to implement it on my own.

**Comment by IeuanWalker** [comment]
@ludas96 Setting the property 'AnimationSpeed' to 0, will disable the animation.

**Comment by ludas96** [comment]
@IeuanWalker It's for the NavigationPage, it's set to PushAsync(page, True) <- where True indicates to use animations.
I've decided to add it myself though so it's fine :)
