### ISSUE TITLE
Allow override breadcrumb text & adjust the margin of text

### ISSUE THREAD

**Issue by zuhry** [IeuanWalker/Xamarin.Forms.Breadcrumb#9]
is this component allow to override the breadcrumb text, as i know, the new breadcrumb text comes from label text. and please add method/properties to adjust the padding or margin between text

**Comment by IeuanWalker** [comment]
@zuhry nice suggestion.

I haven't got much time to look at adding this right now.
But happy to receive a PR for it.

**Comment by IeuanWalker** [comment]
@zuhry available in version 2.4.0
